export const SheetNames = {
  HOMBRES: 'Hombres',
  MUJERES: 'Mujeres',
  HOMBRES_MENORES: 'Hombres<1',
  MUJERES_MENORES: 'Mujeres<1',
};

export const extraDataIDs = {
  minLowPrev: 'minorLowPrevalence',
  minModPrev: 'minorModeratePrevalence',
  minIntPrev: 'minorIntensePrevalence',
  lowPercDiff: 'lowPercentageDifference',
  intPercDiff: 'intensePercentageDifference',
  urbPopPerc: 'urbanPopulation',
  rurPopPerc: 'ruralPopulation',
  urbAdultActPerc: 'urbanActivePALPercentage',
  urbAdultLowPerc: 'urbanLowPALPercentage',
  rurAdultActPerc: 'ruralActivePALPercentage',
  rurAdultLowPerc: 'ruralLowPALPercentage',
  urbAdultActVal: 'ruralActivePALValue',
  urbAdultLowVal: 'ruralLowPALValue',
  rurAdultActVal: 'urbanActivePALValue',
  rurAdultLowVal: 'urbanLowPALValue',
  popCountry: 'countryPopulation',
  pop18to29Fem: '18to29FemaleCountryPopulation',
  pop30to59Fem: '30to59FemaleCountryPopulation',
  birthRate: 'birthRate',
  extraEnergyPreg18to29: 'pregnancyExtraEnergy18to29',
  extraEnergyLact18to29: 'lactationExtraEnergy18to29',
  extraEnergyPreg30to59: 'pregnancyExtraEnergy30to59',
  extraEnergyLact30to59: 'lactationExtraEnergy30to59',
}